#
# Copyright (C) 2021-2022 Intel Corporation
# Copyright (C) 2022 CVAT.ai Corporation
#
# SPDX-License-Identifier: MIT
#

services:
  cvat_server:
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        socks_proxy:
        CLAM_AV:
        INSTALL_SOURCES:
        CVAT_DEBUG_ENABLED:
    environment:
      CVAT_DEBUG_ENABLED: '${CVAT_DEBUG_ENABLED:-no}'
      CVAT_DEBUG_PORT: '9090'
      # If 'yes', wait for a debugger connection on startup
      CVAT_DEBUG_WAIT: '${CVAT_DEBUG_WAIT_CLIENT:-no}'
    ports:
      - '9090:9090'

  cvat_worker_export:
    environment:
      # For debugging, make sure to set 1 process
      # Due to the supervisord specifics, the extra processes will fail and
      # after few attempts supervisord will give up restarting, leaving only 1 process
      # NUMPROCS: 1
      CVAT_DEBUG_ENABLED: '${CVAT_DEBUG_ENABLED:-no}'
      CVAT_DEBUG_PORT: '9092'
    ports:
      - '9092:9092'

  cvat_worker_import:
    environment:
      # For debugging, make sure to set 1 process
      # Due to the supervisord specifics, the extra processes will fail and
      # after few attempts supervisord will give up restarting, leaving only 1 process
      # NUMPROCS: 1
      CVAT_DEBUG_ENABLED: '${CVAT_DEBUG_ENABLED:-no}'
      CVAT_DEBUG_PORT: '9093'
    ports:
      - '9093:9093'

  cvat_worker_annotation:
    environment:
      # For debugging, make sure to set 1 process
      # Due to the supervisord specifics, the extra processes will fail and
      # after few attempts supervisord will give up restarting, leaving only 1 process
      # NUMPROCS: 1
      CVAT_DEBUG_ENABLED: '${CVAT_DEBUG_ENABLED:-no}'
      CVAT_DEBUG_PORT: '9091'
    ports:
      - '9091:9091'

  cvat_ui:
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
      dockerfile: Dockerfile.ui

  cvat_opa:
    ports:
      - '8181:8181'
