{{- if .Values.cvat.backend.server.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ tpl ( .Values.cvat.backend.server.secret.name) . }}"
  namespace: {{ .Release.Namespace }}
type: generic
stringData:
  googleClientId: {{ .Values.cvat.backend.server.secret.socialAccountAuthentication.googleClientId | quote }}
  googleClientSecret: {{ .Values.cvat.backend.server.secret.socialAccountAuthentication.googleClientSecret | quote }}
  githubClientId: {{ .Values.cvat.backend.server.secret.socialAccountAuthentication.githubClientId | quote }}
  githubClientSecret: {{ .Values.cvat.backend.server.secret.socialAccountAuthentication.githubClientSecret | quote }}
{{- end }}