additionalProperties:
  projectName: "cvat_sdk"
  packageVersion: "2.0-alpha"
  packageUrl: "https://github.com/cvat-ai/cvat"
  packageName: "cvat_sdk.api_client"
  initRequiredVars: true
  generateSourceCodeOnly: false
  generatorLanguageVersion: '>=3.7'
globalProperties:
  generateAliasAsModel: true
  apiTests: false
  modelTests: false
